### ISSUE TITLE
天地图更新后，需要授权，无法使用

### ISSUE THREAD

**Issue by giszh86** [wshunli/arcgis-android-tianditu#1]
无法加载显示

**Comment by wshunli** [comment]
天地图前时间进行了更新，需要在请求 URl 后添加授权信息，依赖还未更新，非常抱歉。

http://lbs.tianditu.gov.cn/authorization/authorization.html#example

**Comment by wshunli** [comment]
本依赖已更新，请使用 2.1.0 版本。

**Comment by giszh86** [comment]
可以用了，非常感谢。
