### ISSUE TITLE
TianDiTuLayer中拼接字符串的tileUrlBuffer定义错误

### ISSUE THREAD

**Issue by ok958726** [wshunli/arcgis-android-tianditu#4]
TianDiTuLayer中拼接字符串的tileUrlBuffer定义成了全局，每次执行tileUrlBuffer.append(layerInfo.getUrl()).......后，虽然setLength(0)，但是还是会出现地址不断追加的情况，导致请求失败。

**Comment by wshunli** [comment]
可以使用 2.2.0 最新版的，修复了这些问题
