### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by wernety** [wshunli/arcgis-android-tianditu#5]
一、在学习运行您的框架过程中，我始终执行不了下面四句话（位于arcgis-android-tianditu-master\sample\src\main\java\com\wshunli\map\tianditu\sample\MainActivity.java)

import com.esri.arcgisruntime.layers.WebTiledLayer;
import com.esri.arcgisruntime.mapping.ArcGISMap;
import com.esri.arcgisruntime.mapping.Basemap;
import com.esri.arcgisruntime.mapping.view.MapView;

在项目里的gradle里面我按照您的说明配置了在线 ArcGIS，并且在sample和tianditu这两个module下面也按照您的说明配置了依赖 ，但是它们好像不起作用，于是我想请问有什么方法可以解决的吗？

二、另外，在阅读您的代码的时候，我一直在寻找MainActivity.java中导入的四个文件的位置（MainActivity.java位于arcgis-android-tianditu-master\sample\src\main\java\com\wshunli\map\tianditu\sample\MainActivity.java）
com.lxj.xpopup.XPopup;
com.lxj.xpopup.impl.BottomListPopupView;
com.lxj.xpopup.impl.CenterListPopupView;
com.lxj.xpopup.interfaces.OnSelectListener;
请问这四个文件在哪个位置下呢？

最后，由于我是初学者，所以提的问题比较简单，希望您见谅，谢谢您，祝安好

**Comment by wshunli** [comment]
一、ArcGIS Android 依赖的问题

检查下依赖的配置，然后做下 Gradle Sync 

二、xpopup 只是 demo 中使用

可以根据项目需要选择
```
 implementation 'com.lxj:xpopup:1.9.0'
```
